Repository HumanSignal/label-studio-converter, pull requests merged in 2022-08, with the labels that each got.

#120 fix: DEV-3164: Remove potential data exposure from logs
  label_studio_converter/audio.py
  label_studio_converter/converter.py
  label_studio_converter/imports/yolo.py
  label_studio_converter/utils.py
Labels: fix

#122 ci: DEV-3193: Fix version replace
  .github/workflows/build_pypi.yml
  .github/workflows/cut-off-release-branch.yml
Labels: title needs formatting, ci

#123 ci: Fix version in setup.py and sync .github
  .github/workflows/build_pypi.yml
  .github/workflows/cut-off-release-branch.yml
  setup.py
Labels: ci

#124 ci: Fix exit code in cutoff workflow
  .github/workflows/cut-off-release-branch.yml
Labels: ci
