Repository HumanSignal/label-studio-converter, pull requests merged in 2023-04, with the labels that each got.

#213 Bump version to 0.0.52
  label_studio_converter/__init__.py
Labels: title needs formatting

#214 ci: Fix workflow call branch
  .github/workflows/release-cut-off-release-branch.yml
Labels: ci

#215 fix: LSDV-4631: Post-fix for CSV converter and json items iterator to prevent high memory usage, postfix with while
  label_studio_converter/__init__.py
  label_studio_converter/utils.py
Labels: fix

#216 ci: Fix version regexp
  .github/workflows/release-set-version.yml
Labels: ci
