Repository HumanSignal/label-studio-converter, pull requests merged in 2024-06, with the labels that each got.

#287 feat: Support for exporting to YOLO OBB format
  label_studio_converter/converter.py
  label_studio_converter/main.py
  label_studio_converter/utils.py
  tests/data/test_export_yolo/data_obb.json
  tests/data/test_export_yolo/label_config_obb.xml
  tests/test_export_yolo.py
Labels: feat

#294 fix: pytests
  .github/workflows/tests.yml
  tests/test_export_yolo.py
  tests/test_import_yolo.py
  tests/utils.py
Labels: fix

#296 docs: Update README.md
  README.md
Labels: title needs formatting
